import type { ProjectSeed } from './types.js';

const SILVER_PINES_NAV = [
  { label: 'Home', href: '/', icon: 'home', public: true },
  { label: 'Daily Schedule', href: '/page.html?slug=daily-schedule', icon: 'calendar', public: true },
  { label: 'Getting Here', href: '/page.html?slug=getting-here', icon: 'map', public: true },
  { label: 'Block Showcase', href: '/page.html?slug=showcase', icon: 'star', public: true },
  { label: 'Our Members', href: '/directory.html', icon: 'users', public: true },
  { label: 'Events', href: '/events.html', icon: 'calendar', feature: 'feature_events' },
  {
    label: 'Resources',
    href: '/resources.html',
    icon: 'book-open',
    feature: 'feature_resources',
    children: [
      { label: 'Transportation', href: '/resources.html?category=Transportation', public: true },
      { label: 'Health', href: '/resources.html?category=Health', public: true },
      { label: 'Meals', href: '/resources.html?category=Meals', public: true },
      { label: 'Technology', href: '/resources.html?category=Technology', public: true },
    ],
  },
  { label: 'Forum', href: '/forum.html', icon: 'message-circle', feature: 'feature_forum' },
  { label: 'Polls', href: '/polls.html', icon: 'bar-chart', feature: 'feature_polls' },
  { label: 'Committees', href: '/committees.html', icon: 'briefcase', feature: 'feature_committees' },
  { label: 'Announcements', href: '/#announcements-section', icon: 'bell', public: true },
  { label: 'Dashboard', href: '/admin.html', icon: 'bar-chart-2', admin: true },
  { label: 'Members', href: '/admin-members.html', icon: 'users', admin: true },
  { label: 'Settings', href: '/admin-settings.html', icon: 'settings', admin: true },
];

const GETTING_HERE_HTML = `<div style="max-width:52rem"><p style="font-size:1.25rem;color:var(--color-text-muted);margin-bottom:2rem">142 Pine Street, Asheville, NC 28801 &bull; Open Mon-Fri 8am-5pm &bull; <strong>828-555-0100</strong></p><div class="mb-2" style="border-radius:var(--radius,8px);overflow:hidden"><iframe src="https://maps.google.com/maps?q=142+Pine+Street,+Asheville,+NC+28801&t=&z=15&ie=UTF8&iwloc=&output=embed" width="100%" height="300" style="border:0;display:block" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div><div class="card mb-2" style="padding:2rem"><h3 style="margin-bottom:1rem">By Car</h3><p>From <strong>I-240</strong>, take Exit 5A (Merrimon Ave). Go south 0.5 miles, turn right on Pine Street. The center is on the left.</p><p><strong>Parking:</strong> Free lot behind the building (enter from Pine Street). 4 accessible parking spaces by the front entrance.</p></div><div class="card mb-2" style="padding:2rem"><h3 style="margin-bottom:1rem">Silver Pines Shuttle</h3><p>Our <strong>free shuttle</strong> runs Monday-Friday with 3 routes covering North Asheville, West Asheville, and South Asheville.</p><ul style="margin:1rem 0 1rem 1.5rem"><li><strong>Route A (North):</strong> Montford, Merrimon Ave, North Asheville — Departs 8:15am, 10:15am, 1:15pm</li><li><strong>Route B (West):</strong> West Asheville, Candler, Leicester — Departs 8:30am, 10:30am, 1:30pm</li><li><strong>Route C (South):</strong> Biltmore, South Asheville, Arden — Departs 8:00am, 10:00am, 1:00pm</li></ul><p>Return trips depart the center at 12:00pm, 3:00pm, and 5:00pm. Call Frank at <strong>828-555-0106</strong> to arrange a ride or <a href='/resources.html'>download the full schedule</a>.</p></div><div class="card mb-2" style="padding:2rem"><h3 style="margin-bottom:1rem">Volunteer Driver Program</h3><p>Need a ride to a <strong>medical appointment</strong>? Our volunteer drivers are happy to help. Call the center at <strong>828-555-0100</strong> at least 24 hours in advance. Rides available within 15 miles of Asheville.</p></div><div class="card mb-2" style="padding:2rem"><h3 style="margin-bottom:1rem">Public Transit</h3><p><strong>ART Bus Route 170</strong> stops at Pine &amp; Merrimon (2 minute walk). Route runs every 30 minutes weekdays.</p></div><div class="card mb-2" style="padding:2rem;border-left:4px solid var(--color-primary)"><h3 style="margin-bottom:1rem">Accessibility</h3><p>Silver Pines is <strong>fully wheelchair accessible</strong>. We have:</p><ul style="margin:1rem 0 0 1.5rem"><li>Ramp at the main entrance</li><li>Wide doorways throughout</li><li>Accessible restrooms on both floors</li><li>Elevator to the second floor</li><li>Hearing loop in the Main Hall</li><li>Large-print materials available</li><li>Service animals welcome</li></ul></div></div>`;

const DAILY_SCHEDULE_HTML = `<div style="max-width:60rem"><p style="font-size:1.25rem;color:var(--color-text-muted);margin-bottom:2rem">Drop in anytime! All classes and activities are free for members unless noted.</p><div class="table-wrap"><table><thead><tr><th>Time</th><th>Monday</th><th>Tuesday</th><th>Wednesday</th><th>Thursday</th><th>Friday</th></tr></thead><tbody><tr><td><strong>9:00-10:00</strong></td><td>Chair Yoga</td><td style="background:color-mix(in srgb, var(--color-primary) 8%, transparent)">Tai Chi (George)</td><td>Chair Yoga</td><td style="background:color-mix(in srgb, var(--color-primary) 8%, transparent)">Tai Chi (George)</td><td>Gentle Stretch</td></tr><tr><td><strong>10:00-12:00</strong></td><td>Open Craft Room</td><td style="background:color-mix(in srgb, var(--color-primary) 8%, transparent)">Tech Help Desk</td><td>Open Craft Room</td><td style="background:color-mix(in srgb, var(--color-primary) 8%, transparent)">Tech Help Desk</td><td>Open Craft Room</td></tr><tr><td><strong>11:30-12:30</strong></td><td>Lunch ($3)</td><td>—</td><td>Lunch ($3)</td><td>—</td><td>Lunch ($3)</td></tr><tr><td><strong>1:00-2:00</strong></td><td>Bridge &amp; Cards</td><td>Piano Basics (Mary)</td><td>Bridge &amp; Cards</td><td>Cooking Class (Nancy)</td><td>Bridge &amp; Cards</td></tr><tr><td><strong>2:00-4:00</strong></td><td style="background:color-mix(in srgb, var(--color-primary) 8%, transparent)">Garden Hours</td><td style="background:color-mix(in srgb, var(--color-primary) 8%, transparent)">Garden Hours</td><td style="background:color-mix(in srgb, var(--color-primary) 8%, transparent)">Watercolor (Margaret)</td><td style="background:color-mix(in srgb, var(--color-primary) 8%, transparent)">Garden Hours</td><td style="background:color-mix(in srgb, var(--color-primary) 8%, transparent)">Garden Hours</td></tr><tr><td><strong>3:00-4:30</strong></td><td>—</td><td>—</td><td>—</td><td>Book Club (Evelyn)</td><td>—</td></tr><tr style="border-top:2px solid var(--color-border)"><td><strong>6:30 PM</strong></td><td>—</td><td>—</td><td>—</td><td>—</td><td style="background:color-mix(in srgb, var(--color-primary) 8%, transparent)">Movie Night (2nd &amp; 4th Fri)</td></tr></tbody></table></div><div class="card mt-2" style="padding:1.5rem;border-left:4px solid var(--color-primary)"><p style="margin:0"><strong>Center hours:</strong> Mon-Fri 8am-5pm (6:30pm on Movie Fridays) &bull; <strong>Meal program:</strong> Mon/Wed/Fri 11:30am-12:30pm, $3 suggested donation &bull; <strong>Questions?</strong> Call 828-555-0100</p></div></div>`;

export const seed: ProjectSeed = {
  site_config: {
    site_name: { value: 'Silver Pines Senior Center', category: 'branding' },
    site_tagline: { value: 'Where every day brings something new', category: 'branding' },
    site_description: {
      value:
        "Silver Pines is Asheville's favorite community center for active adults. From tai chi to tech help, watercolors to book clubs, there's always something happening. Join your neighbors for classes, events, and great conversation in the heart of the Blue Ridge.",
      category: 'branding',
    },
    // Logo is square 1024×1024 → brand_icon_url. Picker rule: icon + text.
    brand_text: { value: 'Silver Pines Senior Center', category: 'branding' },
    brand_text_short: { value: 'Silver Pines', category: 'branding' },
    brand_icon_url: { value: '/assets/logo.png', category: 'branding' },
    brand_wordmark_url: { value: '', category: 'branding' },
    favicon_url: { value: '/assets/logo.png', category: 'branding' },
    theme: {
      value: {
        primary: '#5B7F5E',
        primary_hover: '#4A6B4D',
        bg: '#FFFDF7',
        surface: '#F5F0E8',
        text: '#2C2C2C',
        text_muted: '#5A5A5A',
        border: '#D5CFC4',
        font_heading: 'Bitter',
        font_body: 'IBM Plex Sans',
        radius: '0.75rem',
        max_width: '68rem',
      },
      category: 'theme',
    },
    feature_events: { value: true, category: 'features' },
    feature_forum: { value: true, category: 'features' },
    feature_directory: { value: true, category: 'features' },
    feature_resources: { value: true, category: 'features' },
    feature_blog: { value: false, category: 'features' },
    feature_committees: { value: true, category: 'features' },
    feature_reactions: { value: true, category: 'features' },
    feature_activity_feed: { value: true, category: 'features' },
    feature_polls: { value: true, category: 'features' },
    polls_member_create: { value: false, category: 'features' },
    feature_ai_moderation: { value: false, category: 'features' },
    feature_ai_translation: { value: false, category: 'features' },
    feature_ai_newsletter: { value: false, category: 'features' },
    feature_ai_insights: { value: false, category: 'features' },
    feature_ai_onboarding: { value: false, category: 'features' },
    feature_ai_event_recaps: { value: false, category: 'features' },
    directory_public: { value: true, category: 'features' },
    signup_mode: { value: 'open', category: 'features' },
    demo_mode: { value: true, category: 'features' },
  },
  membership_tiers: [
    {
      name: 'Guest',
      description: 'Visitors and prospective members',
      benefits: ['View events', 'Browse resources', 'Visit the center'],
      price_label: 'Free',
      position: 1,
    },
    {
      name: 'Member',
      description: 'Registered community members',
      benefits: ['RSVP to events', 'Forum access', 'Member directory', 'Class enrollment', 'Newsletter'],
      price_label: 'Free',
      position: 2,
      is_default: true,
    },
    {
      name: 'Volunteer',
      description: 'Members who give their time to help others',
      benefits: ['All member benefits', 'Committee membership', 'Volunteer recognition', 'Priority class enrollment'],
      price_label: 'Free',
      position: 3,
    },
    {
      name: 'Board',
      description: 'Center leadership and administration',
      benefits: ['Full access', 'Admin tools', 'Board meetings', 'Budget oversight'],
      price_label: 'By appointment',
      position: 4,
    },
  ],
  member_custom_fields: [
    { field_name: 'phone', field_label: 'Phone Number', field_type: 'text', required: false, visible_in_directory: false, position: 1 },
    { field_name: 'neighborhood', field_label: 'Neighborhood', field_type: 'text', required: false, visible_in_directory: true, position: 2 },
    {
      field_name: 'interests',
      field_label: 'Interests',
      field_type: 'multi_select',
      options: ['gardening', 'reading', 'painting', 'tai chi', 'cooking', 'walking', 'crafts', 'music', 'technology', 'cards'],
      required: false,
      visible_in_directory: true,
      position: 3,
    },
    { field_name: 'emergency_contact', field_label: 'Emergency Contact', field_type: 'text', required: false, visible_in_directory: false, position: 4 },
  ],
  pages: [
    { slug: 'getting-here', title: 'Getting Here', published: true },
    { slug: 'daily-schedule', title: 'Daily Schedule', published: true },
    { slug: 'showcase', title: 'Block Showcase', published: true },
  ],
  sections: [
    // --- Header chrome (global) ---
    {
      page_slug: '*',
      zone: 'header',
      scope: 'global',
      section_type: 'brand_header',
      config: { href: '/' },
      position: 1,
    },
    {
      page_slug: '*',
      zone: 'header',
      scope: 'global',
      section_type: 'nav',
      config: { items: SILVER_PINES_NAV },
      position: 2,
    },
    {
      page_slug: '*',
      zone: 'header',
      scope: 'global',
      section_type: 'sign_in_bar',
      config: { show_lang_toggle: true, show_theme_toggle: true },
      position: 3,
    },
    {
      page_slug: '*',
      zone: 'header',
      scope: 'global',
      section_type: 'site_search',
      config: {
        placeholder: 'Search Silver Pines',
        submit_label: 'Search',
        destination: '/search.html',
        compact: true,
        default_type: 'all',
      },
      position: 4,
    },
    // --- Custom pages content ---
    {
      page_slug: 'getting-here',
      zone: 'main',
      scope: 'page',
      section_type: 'custom',
      config: { html: GETTING_HERE_HTML },
      position: 1,
    },
    {
      page_slug: 'daily-schedule',
      zone: 'main',
      scope: 'page',
      section_type: 'custom',
      config: { html: DAILY_SCHEDULE_HTML },
      position: 1,
    },
    // --- Showcase page: every block-types-catalog entry on one page ---
    // page-scoped header chrome — page_banner appears only on this page.
    {
      page_slug: 'showcase',
      zone: 'header',
      scope: 'page',
      section_type: 'page_banner',
      config: {
        image_url: '/assets/hero.jpg',
        image_alt: 'Silver Pines members gathered in the main hall',
        caption_html: 'A tour of every <strong>block type</strong> — live on Silver Pines',
        height: 'medium',
        overlay_color: 'rgba(20, 30, 20, 0.4)',
      },
      position: 10,
    },
    // 1. Tagline strip — opens the tour with a heritage-style band.
    {
      page_slug: 'showcase',
      zone: 'main',
      scope: 'page',
      section_type: 'tagline_strip',
      config: {
        text: 'Every block on this page is a row in the sections table',
        color_scheme: 'primary',
        size: 'large',
        alignment: 'center',
      },
      position: 1,
    },
    // 2. Promo cards — 3-up grid showcasing program tracks.
    {
      page_slug: 'showcase',
      zone: 'main',
      scope: 'page',
      section_type: 'promo_cards',
      config: {
        heading: 'Promo cards',
        columns: 3,
        items: [
          {
            image_url: '/assets/event-tai-chi.jpg',
            image_alt: 'Members practicing tai chi in the studio',
            title: 'Wellness',
            title_position: 'top',
            cta_text: 'See the schedule',
            cta_href: '/page.html?slug=daily-schedule',
          },
          {
            image_url: '/assets/event-craft-fair.jpg',
            image_alt: 'Members at the annual craft fair',
            title: 'Events',
            title_position: 'top',
            cta_text: 'View calendar',
            cta_href: '/events.html',
          },
          {
            image_url: '/assets/committee-garden.jpg',
            image_alt: 'Members tending the community garden',
            title: 'Volunteer',
            title_position: 'top',
            cta_text: 'Join a committee',
            cta_href: '/committees.html',
          },
        ],
      },
      position: 2,
    },
    // 3. Slideshow — auto-rotating gallery with keyboard + reduced-motion support.
    {
      page_slug: 'showcase',
      zone: 'main',
      scope: 'page',
      section_type: 'slideshow',
      config: {
        heading: 'Slideshow',
        items: [
          { src: '/assets/event-tai-chi.jpg', alt: 'Tai chi class', caption: 'Tai chi every Tuesday & Thursday', href: '' },
          { src: '/assets/event-watercolor.jpg', alt: 'Watercolor class', caption: 'Watercolor with Margaret', href: '' },
          { src: '/assets/event-craft-fair.jpg', alt: 'Craft fair', caption: 'Annual craft fair', href: '' },
          { src: '/assets/event-potluck.jpg', alt: 'Friday potluck', caption: 'Friday potluck nights', href: '' },
        ],
        auto_rotate_seconds: 4,
        show_arrows: true,
        show_dots: true,
        aspect_ratio: '16/9',
        fit: 'cover',
        transition: 'fade',
      },
      position: 3,
    },
    // 4. Events list (sidebar layout) — dynamic; pulls from events table.
    {
      page_slug: 'showcase',
      zone: 'main',
      scope: 'page',
      section_type: 'events_list',
      config: {
        heading: 'Events list — sidebar layout',
        count: 4,
        filter: 'upcoming',
        layout: 'sidebar',
        show_image: false,
        show_location: true,
        show_time: true,
        color_scheme: 'primary',
      },
      position: 4,
    },
    // 5. Events list (grid layout) — same data, different layout.
    {
      page_slug: 'showcase',
      zone: 'main',
      scope: 'page',
      section_type: 'events_list',
      config: {
        heading: 'Events list — grid layout',
        count: 6,
        filter: 'upcoming',
        layout: 'grid',
        show_image: false,
        show_location: true,
        show_time: true,
        color_scheme: 'primary',
      },
      position: 5,
    },
    // 6. Link list (manual mode, rows layout).
    {
      page_slug: 'showcase',
      zone: 'main',
      scope: 'page',
      section_type: 'link_list',
      config: {
        heading: 'Link list — manual, rows',
        source: 'manual',
        layout: 'rows',
        items: [
          { label: 'Volunteer driver sign-up', href: '/resources.html', date: '2026-04-22', badge: 'NEW' },
          { label: 'Spring potluck menu', href: '/resources.html', date: '2026-04-18' },
          { label: 'Medicare Basics (PDF)', href: '/assets/medicare-guide.pdf', date: '2026-04-10', badge: 'PDF' },
          { label: 'About this site', href: 'https://kychon.com', date: '2026-04-01', external: true },
        ],
      },
      position: 6,
    },
    // 7. Link list (resources mode, bullets layout).
    // Auto-updates from the resources table where category='Health'.
    {
      page_slug: 'showcase',
      zone: 'main',
      scope: 'page',
      section_type: 'link_list',
      config: {
        heading: 'Link list — resources mode (Health category)',
        source: 'resources',
        layout: 'bullets',
        filter: { category: 'Health', limit: 5, order: 'newest' },
      },
      position: 7,
    },
    // 8. Tagline strip — different scheme for visual contrast.
    {
      page_slug: 'showcase',
      zone: 'main',
      scope: 'page',
      section_type: 'tagline_strip',
      config: {
        text: 'Add, edit, and reorder any of these blocks via the admin overlay',
        color_scheme: 'dark',
        size: 'medium',
        alignment: 'center',
      },
      position: 8,
    },
    // --- Homepage main ---
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'hero',
      config: {
        heading: 'Welcome to Silver Pines',
        subheading: "Asheville's community center for active adults. Classes, events, friends, and a warm cup of coffee — every day.",
        cta_text: "See What's Happening",
        cta_href: '/events.html',
        bg_image: '/assets/hero.jpg',
      },
      position: 1,
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'stats',
      config: {
        items: [
          { value: '22+', label: 'Active Members', href: '/directory.html' },
          { value: '12+', label: 'Events This Month', href: '/events.html' },
          { value: '5', label: 'Committees' },
          { value: '8', label: 'Years Serving Asheville' },
        ],
      },
      position: 2,
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'features',
      config: {
        columns: 3,
        items: [
          { icon: 'calendar', title: 'Classes & Events', desc: "Tai chi, watercolor, book club, tech help, movie nights, and more — there's always something to do." },
          { icon: 'users', title: 'A Real Community', desc: '22 members and growing. Make friends, share skills, and look out for each other.' },
          { icon: 'home', title: 'Your Second Home', desc: 'A warm, accessible space in the heart of Asheville with a garden, art room, and the best coffee in town.' },
        ],
      },
      position: 3,
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'testimonials',
      config: {
        items: [
          { quote: 'Silver Pines gave me a reason to get out of the house every day. I have more friends now than I did at 40.', name: 'Grace Lee', role: 'Member since 2025' },
          { quote: 'The Tech Buddies program changed my life. I can finally video call my grandkids in California!', name: 'Mary Jackson', role: 'Member since 2024' },
          { quote: "I was nervous about retiring. Now I'm busier than ever — garden committee, walking group, and I just started painting!", name: 'Richard Harris', role: 'Member since 2025' },
        ],
      },
      position: 4,
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'embed',
      config: {
        heading: 'Asheville Weather',
        provider: 'weather',
        params: { lat: 35.5951, lon: -82.5515, units: 'imperial', location: 'Asheville, NC' },
        height: '360px',
        responsive: false,
      },
      position: 5,
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'tagline_strip',
      config: {
        text: 'Welcoming Asheville since 2017 — drop in any weekday',
        color_scheme: 'primary',
        size: 'medium',
        alignment: 'center',
      },
      position: 6,
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'promo_cards',
      config: {
        heading: 'Find your fit',
        columns: 3,
        items: [
          {
            image_url: '/assets/event-tai-chi.jpg',
            image_alt: 'Members practicing tai chi in the studio',
            title: 'Classes & Wellness',
            title_position: 'top',
            cta_text: 'See the schedule',
            cta_href: '/page.html?slug=daily-schedule',
          },
          {
            image_url: '/assets/event-craft-fair.jpg',
            image_alt: 'Members at the craft fair sharing handmade goods',
            title: 'Events & Activities',
            title_position: 'top',
            cta_text: 'View upcoming events',
            cta_href: '/events.html',
          },
          {
            image_url: '/assets/committee-garden.jpg',
            image_alt: 'Members tending the community garden',
            title: 'Volunteer & Lead',
            title_position: 'top',
            cta_text: 'Join a committee',
            cta_href: '/committees.html',
          },
        ],
      },
      position: 7,
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'events_list',
      config: {
        heading: 'Upcoming events',
        count: 4,
        filter: 'upcoming',
        layout: 'sidebar',
        show_image: false,
        show_location: true,
        show_time: true,
        color_scheme: 'primary',
      },
      position: 8,
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'announcements_feed',
      config: { heading: 'Announcements', limit: 20 },
      position: 9,
      // column-span-rows: announcements + recent activity side-by-side.
      column_span: '2/3',
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'activity_feed',
      config: { limit: 15 },
      position: 10,
      column_span: '1/3',
    },
    {
      page_slug: 'index',
      zone: 'main',
      scope: 'page',
      section_type: 'cta',
      config: {
        heading: 'Come Visit Us',
        text: 'Silver Pines is open Monday-Friday, 8am-5pm (6:30pm on Movie Fridays). Drop by for a tour, a cup of coffee, and meet your new neighbors.',
        cta_text: 'How to Get Here',
        cta_href: '/page.html?slug=getting-here',
      },
      position: 11,
    },
    // --- Footer chrome (global) ---
    // column-span-rows: address + copyright share a row.
    {
      page_slug: '*',
      zone: 'footer',
      scope: 'global',
      section_type: 'footer_address',
      config: {
        name: 'Silver Pines Senior Center',
        address_lines: ['142 Pine Street', 'Asheville, NC 28801'],
        phone: '828-555-0100',
        email: 'hello@silverpines.org',
        hours: 'Mon–Fri 8am–5pm (6:30pm Movie Fridays)',
      },
      position: 1,
      column_span: '1/2',
    },
    {
      page_slug: '*',
      zone: 'footer',
      scope: 'global',
      section_type: 'footer_copyright',
      config: {
        year: 'auto',
        org_name: 'Silver Pines Senior Center',
        admin_contact_label: 'Contact us',
        admin_contact_href: 'mailto:hello@silverpines.org',
      },
      position: 2,
      column_span: '1/2',
    },
    {
      page_slug: '*',
      zone: 'footer',
      scope: 'global',
      section_type: 'footer_attribution',
      config: { text: 'Powered by [Kychon](https://kychon.com) on [Run402](https://run402.com)' },
      position: 99,
    },
  ],
  extraSqlFile: 'demo/silver-pines/seed.sql',
};
