// Inline the AI connector's guide, input schemas and operation summaries into
// functions/kychon-api.js, which Run402 deploys as one source file.
//
//   npx tsx scripts/generate-connector-schemas.ts          rewrite the block
//   npx tsx scripts/generate-connector-schemas.ts --check  exit 1 if it is stale

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { CONNECTOR_GUIDE_AREAS, CONNECTOR_SCHEMAS } from '../src/lib/capability-api/connector.ts';
import { V1_OPERATION_CATALOG } from '../src/lib/capability-api/operations.ts';

export const KYCHON_API_PATH = 'functions/kychon-api.js';
const BEGIN = '// BEGIN GENERATED: connector guide and schemas (scripts/generate-connector-schemas.ts)';
const END = '// END GENERATED: connector guide and schemas';

export function renderConnectorBlock(): string {
  const summaries = Object.fromEntries(
    [...V1_OPERATION_CATALOG].map((operation) => [operation.name, operation.summary]).sort(([a], [b]) => a.localeCompare(b)),
  );
  // Biome must not reformat the generated JSON, or the drift check would never pass.
  const IGNORE = '// biome-ignore format: generated by scripts/generate-connector-schemas.ts';
  return [
    BEGIN,
    IGNORE,
    `const CONNECTOR_GUIDE_AREAS = ${JSON.stringify(CONNECTOR_GUIDE_AREAS, null, 2)};`,
    IGNORE,
    `const CONNECTOR_SCHEMAS = ${JSON.stringify(CONNECTOR_SCHEMAS, null, 2)};`,
    IGNORE,
    `const OPERATION_SUMMARIES = ${JSON.stringify(summaries, null, 2)};`,
    END,
  ].join('\n');
}

export function applyConnectorBlock(source: string): string {
  const start = source.indexOf(BEGIN);
  const end = source.indexOf(END);
  if (start < 0 || end < start) throw new Error(`${KYCHON_API_PATH} is missing the generated connector markers`);
  return source.slice(0, start) + renderConnectorBlock() + source.slice(end + END.length);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const current = readFileSync(KYCHON_API_PATH, 'utf8');
  const next = applyConnectorBlock(current);
  if (process.argv.includes('--check')) {
    if (next !== current) {
      console.error(`${KYCHON_API_PATH} is stale: run npx tsx scripts/generate-connector-schemas.ts`);
      process.exit(1);
    }
  } else if (next !== current) {
    writeFileSync(KYCHON_API_PATH, next);
    console.log(`updated ${KYCHON_API_PATH}`);
  }
}
