// reset-demo (generated by scripts/generate-reset-function.js, deployed only to
// the demo portals) wipes a demo and reloads its seed. It had no auth check, so
// anyone holding a demo's public anon key could wipe the demo on demand, and a
// burst of calls (a reset takes about 8 of its 15 seconds) could time out and
// fail a deploy's post-deploy error gate. It now runs only when Run402 starts
// it: the hourly schedule, or the owner through Run402. The gateway sets
// x-run402-trigger on those runs and never forwards a caller's x-run402-*
// headers to a function.

import { execFileSync } from 'node:child_process';
import { join } from 'node:path';
import { beforeEach, describe, expect, it, vi } from 'vitest';

const sqlCalls = vi.hoisted(() => [] as string[]);

vi.mock(
  '@run402/functions',
  () => ({
    adminDb: () => ({
      async sql(text: string) {
        sqlCalls.push(text);
        return { rows: [] };
      },
    }),
  }),
  { virtual: true },
);

const RESETS = {
  eagles: () => import('../../demo/eagles/reset-demo.js'),
  'silver-pines': () => import('../../demo/silver-pines/reset-demo.js'),
  'barrio-unido': () => import('../../demo/barrio-unido/reset-demo.js'),
};

beforeEach(() => {
  sqlCalls.length = 0;
});

async function reset(demo: keyof typeof RESETS, headers: Record<string, string> = {}) {
  const handler = (await RESETS[demo]()).default;
  const res = await handler(
    new Request('https://portal.test/functions/v1/reset-demo', { method: 'POST', headers, body: '{}' }),
  );
  return { status: res.status, body: await res.json() };
}

describe.each(Object.keys(RESETS) as Array<keyof typeof RESETS>)('%s reset-demo', (demo) => {
  it('refuses a caller Run402 did not start, before touching the database', async () => {
    expect(await reset(demo)).toEqual({ status: 401, body: { error: 'Unauthorized' } });
    expect(await reset(demo, { 'x-run402-trigger': '' })).toMatchObject({ status: 401 });
    expect(sqlCalls).toEqual([]);
  });

  it('resets the demo for a run Run402 started', async () => {
    const r = await reset(demo, { 'x-run402-trigger': 'function_run' });
    expect(r.status).toBe(200);
    expect(r.body).toMatchObject({ status: 'ok' });
    expect(sqlCalls.some((text) => text.startsWith('TRUNCATE'))).toBe(true);
  });
});

it('the generator emits the gate as the first thing the handler does', () => {
  const source = execFileSync('node', ['scripts/generate-reset-function.js', 'demo/eagles/seed.sql'], {
    cwd: join(import.meta.dirname, '../..'),
    encoding: 'utf8',
  });
  const handler = source.slice(source.indexOf('export default async (req) => {'));
  const gate = handler.indexOf("if (!req.headers.get('x-run402-trigger'))");
  expect(gate).toBeGreaterThan(-1);
  expect(handler.indexOf('adminDb()')).toBeGreaterThan(gate);
});
